version: '3.8'
services:
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_LOGIN: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transformator
    volumes:
      - db-data:/var/lib/mysql:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/transformator:delegated
    links:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/transformator"
      APP_URL: "http://transformator.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "ndu5tb2ald1bt3i2279888xdia13le4b"
      APP_HOSTNAME: "transformator.local"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/transformator:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: